# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  templates:
    name: Format Templates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crates:
          - ./default
          - ./cis2-nft
    env:
      PROJECT_NAME: my-project
    steps:
      - uses: actions/checkout@v2
      - uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          template: ${{ matrix.crates }}
          other: "-d description=myProject -d TOKEN_METADATA_BASE_URL=myProject"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # we need to move the generated project to a temp folder, away from the template project
      # otherwise `cargo` runs would fail
      # see https://github.com/rust-lang/cargo/issues/9922
      - run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo test

  templateComparison:
    name: Format Templates comparison
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crates:
          - ./cis2-nft
    env:
      PROJECT_NAME: my-project
    steps:
      - uses: actions/checkout@v2
      - uses: cargo-generate/cargo-generate-action@v0.16.0
        with:
          name: ${{ env.PROJECT_NAME }}
          template: ${{ matrix.crates }}
          other: "-d description=myProject -d TOKEN_METADATA_BASE_URL=myProject"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # we need to move the generated project to a temp folder, away from the template project
      # otherwise `cargo` runs would fail
      # see https://github.com/rust-lang/cargo/issues/9922
      - run: |
          mv $PROJECT_NAME ${{ runner.temp }}/

      - run: |
          sed -i "s/root/test/g" ${{ runner.temp }}/$PROJECT_NAME/Cargo.toml
          diff /home/runner/work/_temp/$PROJECT_NAME/Cargo.toml compare/cis2-nft/Cargo.toml